---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure directories to export exist
  ansible.builtin.file:
    path: "{{ item.strip().split()[0] }}"
    mode: "0755"
    state: directory
  with_items: "{{ nfs_exports }}"
  when: nfs_exports | length > 0

- name: Ensure NFS Exports file is configured
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Reload NFS Exports
  when: nfs_exports | length > 0

- name: Ensure NFS is running
  ansible.builtin.service:
    name: "{{ nfs_server_daemon }}"
    state: started
    enabled: true
  when: nfs_exports | length > 0
